<a href="https://colab.research.google.com/github/hmmonir/Digital-cafe/blob/master/Handwritten_Digit_Classification_using_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow


In [2]:
pip install keras numpy matplotlib mnist

In [3]:
#keras model
#Activation function
#loss function
#Optimizer

In [8]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import keras
from keras.layers import Dense
from keras.utils import to_categorical
import seaborn

In [9]:
#load Dataset
(xtrain, ytrain), (xtest, ytest)= keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [60]:
xtrain.shape

(60000, 784)

In [ ]:
plt.matshow(xtest[1])

In [ ]:
#Feature Sclaing
#Normalize

xtrain = (xtrain / 255)
xtrain[1]

In [61]:
xtest = xtest / 255
xtest[1]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [62]:
#flatten the images into 28*28 = 784
xtrain = xtrain.reshape(-1,784)
xtest = xtest.reshape(-1,784)
xtrain[1]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [43]:
xtrain.shape

(60000, 784)

In [44]:
#build the model
#sequential
# 3 layers, 1st two layers 64 neuron and relu
#output layer 10 neuron and softmax function
model=keras.Sequential()
model.add(Dense(64, activation='relu', input_dim=784)) #input layer
model.add(Dense(64, activation='relu'))                #hidden layer
model.add(Dense(10, activation='sigmoid'))             #output layer

In [63]:
#compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [46]:
model.fit(xtrain,
          to_categorical(ytrain),
          epochs=20,
          batch_size=32,
          )

Epoch 1/20
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2722 - accuracy: 0.9212
Epoch 2/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1197 - accuracy: 0.9635
Epoch 3/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0877 - accuracy: 0.9732
Epoch 4/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0682 - accuracy: 0.9784
Epoch 5/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0568 - accuracy: 0.9819
Epoch 6/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0479 - accuracy: 0.9849
Epoch 7/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0405 - accuracy: 0.9868
Epoch 8/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0340 - accuracy: 0.9886
Epoch 9/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0314 - accuracy: 0.9894
Epoch 10/20
1875/1875 [==============================] - 9s 5ms/step - loss: 0.025

In [47]:
#evaluate the model
model.evaluate(xtest, to_categorical(ytest))


313/313 [==============================] - 1s 2ms/step - loss: 0.1285 - accuracy: 0.9771


[0.12853331863880157, 0.9771000146865845]

In [48]:
pred=model.predict(xtest)
pred

313/313 [==============================] - 1s 3ms/step


array([[2.16680434e-07, 4.39236028e-04, 2.32328191e-01, ...,
        1.00000000e+00, 2.53551988e-08, 9.33551252e-01],
       [2.75237899e-09, 9.00512695e-01, 1.00000000e+00, ...,
        6.54666055e-09, 7.50583247e-04, 6.69623038e-11],
       [1.93594559e-07, 9.99998689e-01, 1.47488127e-02, ...,
        5.77172935e-01, 2.41807709e-03, 6.99661541e-07],
       ...,
       [2.91099610e-14, 2.86801787e-06, 4.28810286e-12, ...,
        4.17313278e-02, 8.73185869e-04, 5.19503793e-03],
       [2.80822185e-03, 1.89327265e-09, 1.16506005e-08, ...,
        1.23302162e-01, 9.99048650e-01, 2.02361769e-16],
       [1.26328858e-04, 3.36051755e-08, 1.61048224e-08, ...,
        1.39209374e-06, 8.58513469e-11, 1.38264483e-10]], dtype=float32)

In [53]:
np.argmax(pred[1])

2

In [55]:
np.argmax(pred[5])

1